import type { QuizQuestion, QuizTopic } from "@/features/quiz";

export const QUIZ_TOPICS: QuizTopic[] = [
  {
    id: "atomic-bonding",
    label: "Atomic bonding",
    shortLabel: "Bonding",
    description: "Primary and secondary bonds, bond energy, and property links.",
  },
  {
    id: "crystal-structures",
    label: "Crystal structures",
    shortLabel: "Crystals",
    description: "Unit cells, packing, directions, and crystallographic notation.",
  },
  {
    id: "defects-microstructure",
    label: "Defects and microstructure",
    shortLabel: "Defects",
    description: "Point, line, and planar defects and their material consequences.",
  },
  {
    id: "diffusion",
    label: "Diffusion",
    shortLabel: "Diffusion",
    description: "Flux, diffusion mechanisms, and temperature dependence.",
  },
  {
    id: "phase-diagrams",
    label: "Phase diagrams",
    shortLabel: "Phases",
    description: "Phase equilibria, tie lines, lever rule, and invariant reactions.",
  },
  {
    id: "mechanical-properties",
    label: "Mechanical properties",
    shortLabel: "Mechanical",
    description: "Stress-strain behavior, stiffness, strength, and toughness.",
  },
];

export const QUESTION_BANK: QuizQuestion[] = [
  {
    id: "AB-001",
    version: 1,
    status: "reviewed",
    topicId: "atomic-bonding",
    outcomeIds: ["lo.bonding.01"],
    difficulty: "foundation",
    bloom: "understand",
    type: "single-choice",
    stem: "Which description best represents the dominant bonding in crystalline sodium chloride (NaCl)?",
    choices: [
      { id: "a", label: "Shared electron pairs localized between Na and Cl" },
      { id: "b", label: "Electrostatic attraction between Na⁺ and Cl⁻ ions" },
      { id: "c", label: "A sea of delocalized electrons around neutral atoms" },
      { id: "d", label: "Temporary dipoles between nonpolar molecules" },
    ],
    answer: "b",
    explanation:
      "Sodium transfers an electron to chlorine. The resulting oppositely charged ions are held together by nondirectional Coulomb attraction.",
    tags: ["ionic", "primary-bonds", "structure-property"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "AB-002",
    version: 1,
    status: "reviewed",
    topicId: "atomic-bonding",
    outcomeIds: ["lo.bonding.01"],
    difficulty: "intermediate",
    bloom: "analyze",
    type: "multiple-select",
    stem: "Which features of metallic bonding help explain why many metals conduct electricity and deform without immediately fracturing? Select all that apply.",
    choices: [
      { id: "a", label: "Valence electrons are delocalized" },
      { id: "b", label: "The bonding is largely nondirectional" },
      { id: "c", label: "Every bond is a localized electron pair" },
      { id: "d", label: "Metal atoms must carry alternating full positive and negative charges" },
    ],
    answer: ["a", "b"],
    explanation:
      "Mobile, delocalized electrons carry charge, while nondirectional bonding lets atomic planes shift without requiring a fixed set of directional bonds to remain aligned.",
    tags: ["metallic", "conductivity", "ductility"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "AB-003",
    version: 1,
    status: "reviewed",
    topicId: "atomic-bonding",
    outcomeIds: ["lo.bonding.01"],
    difficulty: "foundation",
    bloom: "remember",
    type: "true-false",
    stem: "Van der Waals interactions are classified as primary bonds because they involve permanent electron transfer.",
    answer: false,
    explanation:
      "Van der Waals interactions are secondary bonds arising from dipoles. Permanent electron transfer is characteristic of ionic bonding.",
    tags: ["secondary-bonds", "van-der-waals"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "AB-004",
    version: 1,
    status: "reviewed",
    topicId: "atomic-bonding",
    outcomeIds: ["lo.bonding.01"],
    difficulty: "advanced",
    bloom: "analyze",
    type: "single-choice",
    stem: "On an interatomic energy-versus-separation curve, which feature most directly indicates a high elastic stiffness near equilibrium?",
    choices: [
      { id: "a", label: "A large equilibrium separation" },
      { id: "b", label: "A steep curvature at the energy minimum" },
      { id: "c", label: "A horizontal curve far from equilibrium" },
      { id: "d", label: "A shallow curvature at the energy minimum" },
    ],
    answer: "b",
    explanation:
      "Stiffness is related to the slope of the force-separation curve, equivalently the curvature of the energy curve, at the equilibrium spacing.",
    tags: ["bond-energy", "elastic-modulus"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "CS-001",
    version: 1,
    status: "reviewed",
    topicId: "crystal-structures",
    outcomeIds: ["lo.crystal.01"],
    difficulty: "foundation",
    bloom: "remember",
    type: "single-choice",
    stem: "What is the coordination number of an atom in a perfect face-centered cubic (FCC) crystal?",
    choices: [
      { id: "a", label: "6" },
      { id: "b", label: "8" },
      { id: "c", label: "10" },
      { id: "d", label: "12" },
    ],
    answer: "d",
    explanation:
      "Each atom in an FCC structure has 12 nearest neighbors: four in its plane, four above, and four below.",
    tags: ["fcc", "coordination-number"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "CS-002",
    version: 1,
    status: "reviewed",
    topicId: "crystal-structures",
    outcomeIds: ["lo.crystal.01"],
    difficulty: "intermediate",
    bloom: "apply",
    type: "numeric",
    stem: "Enter the atomic packing factor of a body-centered cubic (BCC) structure as a decimal.",
    answer: 0.68,
    tolerance: 0.01,
    answerNote: "accepted within ±0.01",
    explanation:
      "A BCC unit cell contains two atoms and has a = 4r/√3, giving an atomic packing factor of π√3/8 ≈ 0.68.",
    tags: ["bcc", "atomic-packing-factor", "calculation"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "CS-003",
    version: 1,
    status: "reviewed",
    topicId: "crystal-structures",
    outcomeIds: ["lo.crystal.01"],
    difficulty: "foundation",
    bloom: "understand",
    type: "true-false",
    stem: "Ideal FCC and HCP structures have the same atomic packing factor, approximately 0.74.",
    answer: true,
    explanation:
      "Both structures are close-packed. They differ in stacking sequence—ABCABC for FCC and ABAB for HCP—not in ideal packing efficiency.",
    tags: ["fcc", "hcp", "close-packing"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "CS-004",
    version: 1,
    status: "reviewed",
    topicId: "crystal-structures",
    outcomeIds: ["lo.crystal.01"],
    difficulty: "intermediate",
    bloom: "understand",
    type: "single-choice",
    stem: "In a cubic crystal, the [110] direction runs along which geometric feature of the unit cell?",
    choices: [
      { id: "a", label: "A cube edge" },
      { id: "b", label: "A face diagonal" },
      { id: "c", label: "The body diagonal" },
      { id: "d", label: "A direction normal to every cube face" },
    ],
    answer: "b",
    explanation:
      "The [110] direction advances one lattice parameter along x, one along y, and none along z, so it lies along a face diagonal.",
    tags: ["miller-indices", "crystal-directions"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "DF-001",
    version: 1,
    status: "reviewed",
    topicId: "defects-microstructure",
    outcomeIds: ["lo.defects.01"],
    difficulty: "foundation",
    bloom: "remember",
    type: "single-choice",
    stem: "A missing atom at a normally occupied lattice site is called what?",
    choices: [
      { id: "a", label: "Vacancy" },
      { id: "b", label: "Edge dislocation" },
      { id: "c", label: "Grain boundary" },
      { id: "d", label: "Stacking fault" },
    ],
    answer: "a",
    explanation:
      "A vacancy is a zero-dimensional point defect created when a normally occupied lattice site is empty.",
    tags: ["point-defects", "vacancy"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "DF-002",
    version: 1,
    status: "reviewed",
    topicId: "defects-microstructure",
    outcomeIds: ["lo.defects.01"],
    difficulty: "intermediate",
    bloom: "understand",
    type: "multiple-select",
    stem: "Which defects make up a Frenkel pair in an ionic crystal? Select all that apply.",
    choices: [
      { id: "a", label: "A vacancy on the ion's original lattice site" },
      { id: "b", label: "The displaced ion at an interstitial site" },
      { id: "c", label: "An extra half-plane of atoms" },
      { id: "d", label: "A macroscopic pore" },
    ],
    answer: ["a", "b"],
    explanation:
      "A Frenkel defect forms when an ion leaves its normal site and occupies an interstitial site, producing a vacancy–interstitial pair.",
    tags: ["point-defects", "frenkel"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "DF-003",
    version: 1,
    status: "reviewed",
    topicId: "defects-microstructure",
    outcomeIds: ["lo.defects.01"],
    difficulty: "intermediate",
    bloom: "understand",
    type: "true-false",
    stem: "A Schottky defect preserves overall charge neutrality by creating a stoichiometric set of oppositely charged ion vacancies.",
    answer: true,
    explanation:
      "In a simple AB ionic solid, paired cation and anion vacancies can preserve both stoichiometry and electrical neutrality.",
    tags: ["schottky", "charge-neutrality"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "DF-004",
    version: 1,
    status: "reviewed",
    topicId: "defects-microstructure",
    outcomeIds: ["lo.defects.01"],
    difficulty: "advanced",
    bloom: "understand",
    type: "single-choice",
    stem: "Which vector specifies the magnitude and direction of lattice distortion associated with a dislocation?",
    choices: [
      { id: "a", label: "Reciprocal lattice vector" },
      { id: "b", label: "Burgers vector" },
      { id: "c", label: "Heat-flux vector" },
      { id: "d", label: "Surface-normal vector" },
    ],
    answer: "b",
    explanation:
      "The Burgers vector is defined from the closure failure of a Burgers circuit and characterizes the dislocation's lattice displacement.",
    tags: ["dislocations", "burgers-vector"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "DI-001",
    version: 1,
    status: "reviewed",
    topicId: "diffusion",
    outcomeIds: ["lo.diffusion.01"],
    difficulty: "foundation",
    bloom: "understand",
    type: "single-choice",
    stem: "In one dimension, why does Fick's first law include a minus sign in J = −D(dC/dx)?",
    choices: [
      { id: "a", label: "Diffusion flux points toward lower concentration" },
      { id: "b", label: "The diffusion coefficient is always negative" },
      { id: "c", label: "Concentration must decrease with time" },
      { id: "d", label: "Atoms move only in the negative x direction" },
    ],
    answer: "a",
    explanation:
      "The concentration gradient points toward increasing concentration; ordinary diffusion flux is down that gradient, toward lower concentration.",
    tags: ["ficks-first-law", "flux"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "DI-002",
    version: 1,
    status: "reviewed",
    topicId: "diffusion",
    outcomeIds: ["lo.diffusion.01"],
    difficulty: "intermediate",
    bloom: "apply",
    type: "single-choice",
    stem: "For D = D₀ exp(−Q/RT), what happens to D when absolute temperature increases while D₀ and Q remain constant?",
    choices: [
      { id: "a", label: "D increases" },
      { id: "b", label: "D decreases" },
      { id: "c", label: "D becomes zero" },
      { id: "d", label: "D changes sign" },
    ],
    answer: "a",
    explanation:
      "As T rises, −Q/RT becomes less negative, so the exponential term and therefore the diffusion coefficient increase.",
    tags: ["arrhenius", "temperature", "diffusivity"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "DI-003",
    version: 1,
    status: "reviewed",
    topicId: "diffusion",
    outcomeIds: ["lo.diffusion.01"],
    difficulty: "intermediate",
    bloom: "apply",
    type: "numeric",
    stem: "Estimate the characteristic diffusion distance √(Dt), in micrometres, for D = 1 × 10⁻¹² m²/s and t = 1 × 10⁴ s.",
    answer: 100,
    tolerance: 2,
    unit: "µm",
    answerNote: "accepted within ±2 µm",
    explanation:
      "√(10⁻¹² × 10⁴) = √(10⁻⁸) = 10⁻⁴ m. Multiplying by 10⁶ µm/m gives 100 µm.",
    tags: ["diffusion-distance", "calculation"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "DI-004",
    version: 1,
    status: "reviewed",
    topicId: "diffusion",
    outcomeIds: ["lo.diffusion.01"],
    difficulty: "advanced",
    bloom: "analyze",
    type: "multiple-select",
    stem: "Why is interstitial diffusion often faster than substitutional vacancy diffusion? Select all that apply.",
    choices: [
      { id: "a", label: "Small interstitial atoms can move without waiting for a substitutional vacancy" },
      { id: "b", label: "Many neighboring interstitial positions may be available" },
      { id: "c", label: "Interstitial motion always has zero activation energy" },
      { id: "d", label: "Interstitial diffusion occurs only in liquids" },
    ],
    answer: ["a", "b"],
    explanation:
      "Interstitial atoms are small and need not exchange with a rare vacant lattice site. Their activation energy is not zero, but it is often lower.",
    tags: ["interstitial", "vacancy", "mechanisms"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "PD-001",
    version: 1,
    status: "reviewed",
    topicId: "phase-diagrams",
    outcomeIds: ["lo.phase.01"],
    difficulty: "intermediate",
    bloom: "apply",
    type: "numeric",
    stem: "In an α + liquid region, Cα = 20 wt%, C₀ = 40 wt%, and CL = 60 wt%. What is the mass fraction of α? Enter a decimal.",
    answer: 0.5,
    tolerance: 0.01,
    answerNote: "accepted within ±0.01",
    explanation:
      "The lever rule gives Wα = (CL − C₀)/(CL − Cα) = (60 − 40)/(60 − 20) = 0.50.",
    tags: ["lever-rule", "two-phase"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "PD-002",
    version: 1,
    status: "reviewed",
    topicId: "phase-diagrams",
    outcomeIds: ["lo.phase.01"],
    difficulty: "foundation",
    bloom: "remember",
    type: "single-choice",
    stem: "How many phases coexist at equilibrium at a binary eutectic invariant point under constant pressure?",
    choices: [
      { id: "a", label: "One" },
      { id: "b", label: "Two" },
      { id: "c", label: "Three" },
      { id: "d", label: "Four" },
    ],
    answer: "c",
    explanation:
      "At the eutectic point, liquid and two solid phases coexist: L ⇌ α + β.",
    tags: ["eutectic", "invariant-reaction"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "PD-003",
    version: 1,
    status: "reviewed",
    topicId: "phase-diagrams",
    outcomeIds: ["lo.phase.01"],
    difficulty: "intermediate",
    bloom: "understand",
    type: "single-choice",
    stem: "In a binary two-phase region at fixed temperature, what do the endpoints of a horizontal tie line provide?",
    choices: [
      { id: "a", label: "The relative amounts of the two phases directly" },
      { id: "b", label: "The compositions of the two phases" },
      { id: "c", label: "The cooling rate of the alloy" },
      { id: "d", label: "The grain sizes of the two phases" },
    ],
    answer: "b",
    explanation:
      "Each endpoint lies on a phase boundary and gives that phase's equilibrium composition. Phase amounts then follow from the lever rule.",
    tags: ["tie-line", "phase-composition"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "PD-004",
    version: 1,
    status: "reviewed",
    topicId: "phase-diagrams",
    outcomeIds: ["lo.phase.01"],
    difficulty: "advanced",
    bloom: "apply",
    type: "true-false",
    stem: "For a one-component system with two phases in equilibrium at constant pressure, the condensed phase rule gives zero compositional/temperature degrees of freedom.",
    answer: true,
    explanation:
      "The condensed phase rule is F = C − P + 1. With C = 1 and P = 2, F = 0 at constant pressure.",
    tags: ["gibbs-phase-rule", "equilibrium"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "MP-001",
    version: 1,
    status: "reviewed",
    topicId: "mechanical-properties",
    outcomeIds: ["lo.mechanical.01"],
    difficulty: "foundation",
    bloom: "understand",
    type: "single-choice",
    stem: "On an engineering stress-strain curve, Young's modulus is obtained from which feature?",
    choices: [
      { id: "a", label: "The slope of the initial linear elastic region" },
      { id: "b", label: "The area under only the plastic region" },
      { id: "c", label: "The maximum strain after fracture" },
      { id: "d", label: "The horizontal distance to the ultimate strength" },
    ],
    answer: "a",
    explanation:
      "For linear elastic loading, σ = Eε, so Young's modulus E is the stress-strain slope before yielding.",
    tags: ["youngs-modulus", "stress-strain"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "MP-002",
    version: 1,
    status: "reviewed",
    topicId: "mechanical-properties",
    outcomeIds: ["lo.mechanical.01"],
    difficulty: "foundation",
    bloom: "understand",
    type: "single-choice",
    stem: "Which quantity is represented by the total area under a stress-strain curve up to fracture?",
    choices: [
      { id: "a", label: "Hardness" },
      { id: "b", label: "Toughness per unit volume" },
      { id: "c", label: "Poisson's ratio" },
      { id: "d", label: "Thermal diffusivity" },
    ],
    answer: "b",
    explanation:
      "The integral of stress with respect to strain up to fracture is the energy absorbed per unit volume—material toughness.",
    tags: ["toughness", "energy-absorption"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "MP-003",
    version: 1,
    status: "reviewed",
    topicId: "mechanical-properties",
    outcomeIds: ["lo.mechanical.01"],
    difficulty: "intermediate",
    bloom: "understand",
    type: "true-false",
    stem: "Loading a metal beyond its yield strength generally leaves permanent strain after the load is removed.",
    answer: true,
    explanation:
      "Beyond yield, plastic deformation occurs. Elastic strain recovers during unloading, but the plastic component remains.",
    tags: ["yield-strength", "plastic-deformation"],
    reviewedAt: "2026-08-06",
  },
  {
    id: "MP-004",
    version: 1,
    status: "reviewed",
    topicId: "mechanical-properties",
    outcomeIds: ["lo.mechanical.01"],
    difficulty: "intermediate",
    bloom: "apply",
    type: "numeric",
    stem: "A tensile specimen carries 10 kN over an original cross-sectional area of 100 mm². What is the engineering stress in MPa?",
    answer: 100,
    tolerance: 1,
    unit: "MPa",
    answerNote: "accepted within ±1 MPa",
    explanation:
      "Engineering stress is F/A₀ = 10,000 N / 100 mm² = 100 N/mm². Since 1 N/mm² = 1 MPa, the stress is 100 MPa.",
    tags: ["engineering-stress", "calculation"],
    reviewedAt: "2026-08-06",
  },
];

export const TOPIC_BY_ID = Object.fromEntries(
  QUIZ_TOPICS.map((topic) => [topic.id, topic]),
) as Record<string, QuizTopic>;
